from .event import *
from .dishes import *
from .admin_tg import *
from .book_table import *
from .site import *
from .restourant import *
from .chef import *
from .hours import *
from  .category import *
from .comments import *
from .client_conn import *